/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id 'base'
}

allprojects {
    group = 'org.apache.xerces'
    version = '2.12.3'
    description = 'Apache Xerces-J XML Parser'
}

subprojects {
    apply plugin: 'java-library'

    java {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
        withSourcesJar()
        withJavadocJar()
        if (project.hasProperty('testJavaVersion')) {
            toolchain {
                languageVersion = JavaLanguageVersion.of(project.property('testJavaVersion') as int)
            }
        }
    }

    repositories {
        mavenCentral()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    tasks.withType(Javadoc).configureEach {
        options.encoding = 'UTF-8'
        options.tags = [
            'xerces.internal:a:Internal:',
            'xerces.experimental:a:Experimental:'
        ]
        if (options instanceof CoreJavadocOptions) {
            options.addStringOption('Xdoclint:none', '-quiet')
        }
    }

    tasks.withType(Jar).configureEach {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        from(rootProject.rootDir) {
            include 'LICENSE', 'NOTICE'
            into 'META-INF'
        }
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
        workingDir = rootProject.rootDir

        systemProperty 'javax.xml.parsers.DocumentBuilderFactory', 'org.apache.xerces.jaxp.DocumentBuilderFactoryImpl'
        systemProperty 'javax.xml.parsers.SAXParserFactory', 'org.apache.xerces.jaxp.SAXParserFactoryImpl'
        systemProperty 'javax.xml.validation.SchemaFactory:http://www.w3.org/2001/XMLSchema', 'org.apache.xerces.jaxp.validation.XMLSchemaFactory'

        testLogging {
            events 'passed', 'skipped', 'failed'
            showStandardStreams = false
        }
    }
}
